name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore_odm_generator/cloud_firestore_odm_generator
version: 1.0.0-dev.5

environment:
  sdk: ">=2.14.0-0.0.dev <3.0.0"

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.1
  build_config: ^1.0.0
  cloud_firestore_odm: ^1.0.0-dev.5
  collection: ^1.15.0-nullsafety.5
  json_annotation: ^4.0.0
  meta: 1.2.4
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  expect_error: ^1.0.0
  json_serializable: ^5.0.0
  matcher: ^0.12.10
  test: ^1.16.8
