name: firebase_in_app_messaging
description: Flutter plugin for Firebase In-App Messaging.
version: 0.6.0+5
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_in_app_messaging

false_secrets:
  - example/**

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_in_app_messaging_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_in_app_messaging/firebase_in_app_messaging_platform_interface
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: null
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.inappmessaging
        pluginClass: FirebaseInAppMessagingPlugin
      ios:
        pluginClass: FirebaseInAppMessagingPlugin
