name: firebase_database_platform_interface
description: A common platform interface for the firebase_database plugin.
version: 0.2.0+3
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database_platform_interface

dependencies:
  collection: ^1.15.0-nullsafety.5
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  meta: 1.2.4
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  firebase_core_platform_interface: ^4.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"
