name: firebase_core_platform_interface
description: A common platform interface for the firebase_core plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.2.3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  collection: ^1.15.0-nullsafety.5
  flutter:
    sdk: flutter
  meta: 1.2.4
  plugin_platform_interface: ^1.0.3

