name: firebase_app_check_platform_interface
description: A common platform interface for the firebase_app_check plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_platform_interface
version: 0.0.3+3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  meta: 1.2.4
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  firebase_core_platform_interface: ^4.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
