name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://firebase.flutter.dev/docs/analytics/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 9.0.4

false_secrets:
 - example/**

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_analytics_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics
  firebase_analytics_web:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.analytics
        pluginClass: FlutterFirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin
      macos:
        pluginClass: FLTFirebaseAnalyticsPlugin
      web:
        default_package: firebase_analytics_web
