name: firebase_performance
description:
  Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://firebase.flutter.dev/docs/performance/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance
version: 0.8.0+3

false_secrets:
  - example/**

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_performance_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_performance/firebase_performance_platform_interface
  firebase_performance_web:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_performance/firebase_performance_web
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.performance
        pluginClass: FlutterFirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin
      web:
        default_package: firebase_performance_web
