name: firebase_performance_platform_interface
description:  A common platform interface for the firebase_performance plugin.
version: 0.1.0+3
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
