name: firebase_performance_platform_interface
description:  A common platform interface for the firebase_performance plugin.
version: 0.1.0+3
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.3
