name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'

dependencies:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_storage:
    path: ../
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  image_picker_for_web: ^2.1.4

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web
  firebase_storage:
    path: ../
  firebase_storage_platform_interface:
    path: ../../firebase_storage_platform_interface
  firebase_storage_web:
    path: ../../firebase_storage_web

dev_dependencies:
  drive: ^1.0.0-1.0.nullsafety.1
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
