name: firebase_messaging_platform_interface
description: A common platform interface for the firebase_messaging plugin.
version: 3.1.4
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_platform_interface

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: 1.2.4
  plugin_platform_interface: ^1.0.3
