name: firebase_remote_config_web
description: The web implementation of firebase_remote_config
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_web

version: 1.0.3

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  firebase_core: ^1.10.0
  firebase_core_web: ^1.5.3
  firebase_remote_config_platform_interface: ^1.0.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseRemoteConfigWeb
        fileName: firebase_remote_config_web.dart
