name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://firebase.flutter.dev/docs/messaging/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging
version: 11.2.4

false_secrets:
  - example/**

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_messaging_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_platform_interface
  firebase_messaging_web:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging_web
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.6

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
