name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 2.4.4
homepage: https://firebase.flutter.dev/docs/crashlytics/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics

false_secrets:
  - example/**

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_crashlytics_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_crashlytics/firebase_crashlytics_platform_interface
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
      macos:
        pluginClass: FLTFirebaseCrashlyticsPlugin
