name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics:
    path: ../../../firebase_analytics/firebase_analytics
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_in_app_messaging:
    path: ../
  firebase_in_app_messaging_platform_interface:
    path: ../../firebase_in_app_messaging_platform_interface
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web
  firebase_in_app_messaging_platform_interface:
    path: ../../firebase_in_app_messaging_platform_interface

dev_dependencies:
  drive: 1.0.0-1.0.nullsafety.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  uses-material-design: true
