name: firebase_ml_model_downloader
description: A Flutter plugin allowing you to use Firebase Ml Model Downloader.
version: 0.1.0+4
homepage: https://firebase.flutter.dev/docs/ml/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_model_downloader/firebase_ml_model_downloader

false_secrets:
  - example/**

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_core: ^1.10.0
  firebase_core_platform_interface: ^4.2.3
  firebase_ml_model_downloader_platform_interface: ^0.1.0+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^1.0.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebase_ml_model_downloader
        pluginClass: FirebaseModelDownloaderPlugin
      ios:
        pluginClass: FirebaseModelDownloaderPlugin
      macos:
        pluginClass: FirebaseModelDownloaderPlugin
