name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore_odm/cloud_firestore_odm
version: 1.0.0-dev.5

false_secrets:
  - example/**

environment:
  sdk: ">=2.14.0-0.0.dev <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  flutter:
    sdk: flutter
  meta: 1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
