name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_dynamic_links:
    path: ../
  firebase_dynamic_links_platform_interface:
    path: ../../firebase_dynamic_links_platform_interface

dev_dependencies:
  drive: 1.0.0-1.0.nullsafety.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
