name: firebase_remote_config
description:
  Flutter plugin for Firebase Remote Config. Update your application look and feel and behavior without
  re-releasing.
homepage: https://firebase.flutter.dev/docs/remote-config/overview
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config
version: 1.0.3

false_secrets:
  - example/**

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_remote_config_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_remote_config/firebase_remote_config_platform_interface
  firebase_remote_config_web:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_remote_config/firebase_remote_config_web
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebaseremoteconfig
        pluginClass: FirebaseRemoteConfigPlugin
      ios:
        pluginClass: FLTFirebaseRemoteConfigPlugin
      macos:
        pluginClass: FLTFirebaseRemoteConfigPlugin
