name: firebase_analytics_web
description: The web implementation of firebase_analytics
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_web
version: 0.4.0+4

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  firebase_analytics_platform_interface: ^3.0.3
  firebase_core: ^1.10.0
  firebase_core_web: ^1.5.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAnalyticsWeb
        fileName: firebase_analytics_web.dart
