name: cloud_functions_platform_interface
description: A common platform interface for the cloud_functions plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_platform_interface

# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 5.0.19

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  meta: 1.2.4
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  firebase_core_platform_interface: ^4.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

