name: firebase_performance_web
description: A new Flutter package project.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance/firebase_performance_web
version: 0.1.0+3

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  firebase:
    git:
      url: git@github.com:stanojevicboban/firebase-dart.git
      path: firebase
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  firebase_core_web:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_web
  firebase_performance_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_performance/firebase_performance_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebasePerformanceWeb
        fileName: firebase_performance_web.dart

