name: firebase_dynamic_links_platform_interface
description: A common platform interface for the firebase_dynamic_links plugin.
version: 0.2.0+3
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core: ^1.10.3
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.6
  plugin_platform_interface: ^1.0.1


dev_dependencies:
  firebase_core_platform_interface: ^4.2.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
