name: firebase_analytics_platform_interface
description: A common platform interface for the firebase_analytics plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics_platform_interface
version: 3.0.3

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: '>=1.9.1+hotfix.5'

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
