name: firebase_remote_config_platform_interface
description: A common platform interface for the firebase_remote_config plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.3

environment:
  sdk: '>=2.12.0-133.0.dev <3.0.0'
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: 1.3.0-nullsafety.6
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: git@github.com:stanojevicboban/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.8.0
